### ISSUE TITLE
TripleDiff: compute diff for two graphs of a store

### ISSUE THREAD

**Issue by k00ni** [k00ni/knorke#10]
Function [computeDiffForTwoGraphs](https://github.com/k00ni/knorke/blob/9b48a457362b99c75a11f268773e8d5a6345fc26/src/Knorke/TripleDiff.php#L53)

**Features**:
* [ ] compute the diff of two graphs in a given store. returning an array, each containing only unique Statement instances of the related graph

Ping: @GeorgesAlkhouri

**Assumed time required:** 2 - 3 hours (i think part of the work is also part of #9)

**Comment by GeorgesAlkhouri** [comment]
Usually, when doing graph comparison you get back 3 things:

- In Both: Containing triples that are in both graphs
- In First: Containing triples that are exclusively in the first graph
- In Second: Containing triples that are exclusively in the second graph

So here we ignore *In Both*?

**Comment by k00ni** [comment]
> So here we ignore In Both?

If one of the graphs gets very crowed, lets say 500.000+, wouldn't that have a very high impact on the performance? For now, lets ignore it, except you know a good reason to include it.

**Comment by GeorgesAlkhouri** [comment]
I think one major problem for graph comparison is the graph canonicalization algorithm. [J. McCusker](https://media.proquest.com/media/pq/classic/doc/3843925611/fmt/ai/rep/NPDF?_s=i4v55NV7mZwjNinnI9RkvIiPefo%3D) showed in his implementation, that graphs without blank nodes have a linear canonicalization runtime and graphs with blank nodes have a polynomial canonicalization runtime, which is bad for big graphs with many blank nodes in them.

**Comment by GeorgesAlkhouri** [comment]
I found a very good implementation for this issue. It is well documented (see the link above) and integrated in a very active RDF library, [rdflib](https://pypi.python.org/pypi/rdflib).

But it is written in Python. We have to decide  if we want to rewrite the [implementation](https://github.com/RDFLib/rdflib/blob/master/rdflib/compare.py) or to let php execute a python script. I prefer the last method, because it is quicker to realise and we don't have to reinvent the wheel.

**Comment by k00ni** [comment]
Only a quick note: Blank node support is **not** necessary for now.

I'd like to avoid running a Python script, even if they already do what we need. I am not familiar with it and don't know how its on our current cloud machine.

What time you think would it need to create a "basic" version of a comparison algorithm?

**Comment by GeorgesAlkhouri** [comment]
I think this might be hard but of course possible. In perspective, the rdflib implementation for graph comparison was a doctoral thesis. Also there is no "basic" version, the core functions for the basic functionality are all needed. 

Inaccurate time estimate: 10 - 20h

**Comment by GeorgesAlkhouri** [comment]
Consider the following two graphs we want to compare:

```
GraphA:
http://set1/S http://set1/P http://set1/O

GraphB: 
http://set1/S http://set1/P http://set1/O
```

I get all the statements from both graphs and want to compare them. If I consider them as triples:

```
http://set1/S http://set1/P http://set1/O -> same hash value
http://set1/S http://set1/P http://set1/O -> same hash value
```

they are equal. But if I consider the statements as quads:

```
http://set1/S http://set1/P http://set1/O http://GraphA/-> different hash value
http://set1/S http://set1/P http://set1/O http://GraphB/-> different hash value
```
they are not equal. So what should be the expected behaviour?

**Comment by k00ni** [comment]
I guess it can be closed.
